# Generated by Django 3.0.8 on 2020-09-09 07:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0003_auto_20200908_1717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tienda',
            new_name='Producto',
        ),
    ]
