# Generated by Django 3.0.8 on 2020-09-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20200909_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
